"""End-to-end research pipeline."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from global_market_lead_lag.backtest import (
    evaluate_strategy_variants,
    run_train_validation_test,
    train_test_backtest,
    walk_forward_backtest,
)
from global_market_lead_lag.config import DEFAULT_STRATEGY_SPECS, MarketConfig
from global_market_lead_lag.data import (
    build_directional_close_to_close_dataset,
    build_japan_us_tradable_dataset,
    download_market_data,
    extract_open_close,
)
from global_market_lead_lag.metrics import performance_stats, strategy_diagnostics, yearly_performance
from global_market_lead_lag.models import regression_summary
from global_market_lead_lag.plots import save_drawdown_curve, save_equity_curve, save_yearly_bar_chart


FEATURE_COL = "feature_sp500_open_to_close"
TARGET_COL = "target_nikkei_open_to_close"
DATE_COL = "japan_date"


def _pct(value: float) -> str:
    return f"{value:.2%}"


def _num(value: float) -> str:
    return f"{value:.2f}"


def _save_table(table: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    index_label = table.index.name or "index"
    table.to_csv(path, index_label=index_label)


def _write_summary(
    path: Path,
    config: MarketConfig,
    directional_corr: pd.DataFrame,
    baseline_regression: pd.DataFrame,
    tvt: dict[str, object],
    wf_summary: pd.DataFrame,
    wf_diagnostics: pd.DataFrame,
    wf_selection_counts: pd.DataFrame,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    selected = tvt["selected"]
    test_results = tvt["test_results"]
    selected_row = test_results.iloc[0]
    benchmark_row = test_results.loc["Buy & Hold"]
    wf_row = wf_summary.loc["Walk-Forward Selected Strategy"]
    wf_benchmark = wf_summary.loc["Buy & Hold"]
    wf_diag = wf_diagnostics.loc["Walk-Forward Selected Strategy"]
    baseline = baseline_regression.loc["US open-to-close -> Japan open-to-close"]

    lines = [
        "# Research Summary",
        "",
        "This report is generated by `scripts/run_research.py`.",
        "",
        "## Setup",
        "",
        f"- Data source: Yahoo Finance via `yfinance`",
        f"- Start date: `{config.start_date}`",
        f"- End date: `{config.end_date or 'latest available'}`",
        "- Signal: S&P 500 open-to-close return from the latest completed U.S. session",
        "- Target: Nikkei 225 open-to-close return during the next Japanese session",
        f"- Base transaction cost: `{config.base_cost_bps:g}` bps per unit of turnover",
        "",
        "## Lead-Lag Evidence",
        "",
        f"- S&P previous session vs Nikkei next session correlation: `{directional_corr.loc['S&P yesterday vs Nikkei today', 'correlation']:.4f}`",
        f"- Baseline regression coefficient: `{baseline['coefficient']:.4f}`",
        f"- Baseline regression p-value: `{baseline['p_value']:.3g}`",
        f"- Baseline regression R-squared: `{baseline['r_squared']:.2%}`",
        "",
        "## Fixed Train/Validation/Test Result",
        "",
        f"- Selected validation strategy: `{selected.name}`",
        f"- Selected strategy annual return: `{_pct(selected_row['annual_return'])}`",
        f"- Selected strategy Sharpe: `{_num(selected_row['sharpe'])}`",
        f"- Selected strategy max drawdown: `{_pct(selected_row['max_drawdown'])}`",
        f"- Buy-and-hold annual return: `{_pct(benchmark_row['annual_return'])}`",
        f"- Buy-and-hold Sharpe: `{_num(benchmark_row['sharpe'])}`",
        f"- Buy-and-hold max drawdown: `{_pct(benchmark_row['max_drawdown'])}`",
        "",
        "## Walk-Forward Result",
        "",
        f"- Walk-forward annual return: `{_pct(wf_row['annual_return'])}`",
        f"- Walk-forward Sharpe: `{_num(wf_row['sharpe'])}`",
        f"- Walk-forward max drawdown: `{_pct(wf_row['max_drawdown'])}`",
        f"- Buy-and-hold annual return over same window: `{_pct(wf_benchmark['annual_return'])}`",
        f"- Buy-and-hold Sharpe over same window: `{_num(wf_benchmark['sharpe'])}`",
        f"- Buy-and-hold max drawdown over same window: `{_pct(wf_benchmark['max_drawdown'])}`",
        f"- Walk-forward exposure: `{_pct(wf_diag['exposure'])}`",
        f"- Walk-forward invested days: `{int(wf_diag['invested_days'])}`",
        "",
        "## Strategy Selection Counts",
        "",
    ]

    for strategy, row in wf_selection_counts.iterrows():
        lines.append(f"- `{strategy}`: {int(row['folds_selected'])} folds")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The evidence supports a modest U.S.-to-Japan lead-lag effect. The signal remains useful in a walk-forward setup, but the advantage is much smaller than the best fixed-split result. Most of the improvement comes from selective exposure and drawdown reduction rather than high daily accuracy.",
            "",
            "This is a research project, not financial advice. Results depend on data quality, transaction-cost assumptions, shorting feasibility, tax treatment, and execution quality.",
            "",
        ]
    )

    path.write_text("\n".join(lines), encoding="utf-8")


def run_pipeline(
    config: MarketConfig | None = None,
    output_dir: str | Path = "reports",
    save_outputs: bool = True,
) -> dict[str, object]:
    """Run the full lead-lag research workflow."""

    config = config or MarketConfig()
    output_dir = Path(output_dir)
    tables_dir = output_dir / "tables"
    figures_dir = output_dir / "figures"

    raw = download_market_data(config.tickers, config.start_date, config.end_date)
    open_prices, close_prices = extract_open_close(raw, config.tickers)
    tradable = build_japan_us_tradable_dataset(open_prices, close_prices)
    lead_lag = build_directional_close_to_close_dataset(close_prices)

    directional_corr = pd.Series(
        {
            "Nikkei today vs S&P today": lead_lag["nikkei"].corr(lead_lag["sp500"]),
            "Nikkei yesterday vs S&P today": lead_lag["nikkei_lag1"].corr(lead_lag["sp500"]),
            "S&P yesterday vs Nikkei today": lead_lag["sp500_lag1"].corr(lead_lag["nikkei"]),
        },
        name="correlation",
    ).to_frame()

    baseline_regression = pd.DataFrame(
        {
            "US open-to-close -> Japan open-to-close": regression_summary(
                tradable,
                FEATURE_COL,
                TARGET_COL,
            )
        }
    ).T

    variant_results, variant_backtests = evaluate_strategy_variants(
        tradable,
        feature_col=FEATURE_COL,
        target_col=TARGET_COL,
        date_col=DATE_COL,
        strategy_specs=DEFAULT_STRATEGY_SPECS,
        split=config.train_split,
        cost_bps=config.base_cost_bps,
    )

    cost_results = {}
    for cost_bps in [0, 2.5, 5, 10, 20, 50]:
        bt_cost, _ = train_test_backtest(
            tradable,
            feature_col=FEATURE_COL,
            target_col=TARGET_COL,
            date_col=DATE_COL,
            mode="long_only",
            threshold=0.0,
            split=config.train_split,
            cost_bps=cost_bps,
        )
        cost_results[f"{cost_bps:g} bps"] = performance_stats(bt_cost["strategy_return"])
    cost_results = pd.DataFrame(cost_results).T

    tvt = run_train_validation_test(
        tradable,
        feature_col=FEATURE_COL,
        target_col=TARGET_COL,
        date_col=DATE_COL,
        strategy_specs=DEFAULT_STRATEGY_SPECS,
        cost_bps=config.base_cost_bps,
    )
    tvt_diagnostics = pd.DataFrame(
        {
            f"Selected Strategy: {tvt['selected'].name}": strategy_diagnostics(tvt["bt_test"])
        }
    ).T

    wf_results, wf_folds = walk_forward_backtest(
        tradable,
        feature_col=FEATURE_COL,
        target_col=TARGET_COL,
        date_col=DATE_COL,
        strategy_specs=DEFAULT_STRATEGY_SPECS,
        cost_bps=config.base_cost_bps,
    )
    wf_summary = pd.DataFrame(
        {
            "Walk-Forward Selected Strategy": performance_stats(wf_results["strategy_return"]),
            "Buy & Hold": performance_stats(wf_results["buy_hold_return"]),
        }
    ).T
    wf_diagnostics = pd.DataFrame(
        {
            "Walk-Forward Selected Strategy": strategy_diagnostics(wf_results),
        }
    ).T
    wf_selection_counts = (
        wf_folds["selected_strategy"].value_counts().rename_axis("strategy").to_frame("folds_selected")
    )
    wf_yearly = yearly_performance(wf_results, DATE_COL)

    outputs = {
        "raw": raw,
        "tradable": tradable,
        "directional_corr": directional_corr,
        "baseline_regression": baseline_regression,
        "variant_results": variant_results,
        "variant_backtests": variant_backtests,
        "cost_results": cost_results,
        "tvt": tvt,
        "tvt_diagnostics": tvt_diagnostics,
        "wf_results": wf_results,
        "wf_folds": wf_folds,
        "wf_summary": wf_summary,
        "wf_diagnostics": wf_diagnostics,
        "wf_selection_counts": wf_selection_counts,
        "wf_yearly": wf_yearly,
    }

    if save_outputs:
        _save_table(tradable, tables_dir / "tradable_dataset.csv")
        _save_table(directional_corr, tables_dir / "directional_correlations.csv")
        _save_table(baseline_regression, tables_dir / "baseline_regression.csv")
        _save_table(variant_results, tables_dir / "strategy_variants.csv")
        _save_table(cost_results, tables_dir / "cost_sensitivity.csv")
        _save_table(tvt["validation_results"], tables_dir / "validation_results.csv")
        _save_table(tvt["test_results"], tables_dir / "test_results.csv")
        _save_table(tvt_diagnostics, tables_dir / "test_diagnostics.csv")
        _save_table(wf_results, tables_dir / "walk_forward_returns.csv")
        _save_table(wf_folds, tables_dir / "walk_forward_folds.csv")
        _save_table(wf_summary, tables_dir / "walk_forward_summary.csv")
        _save_table(wf_diagnostics, tables_dir / "walk_forward_diagnostics.csv")
        _save_table(wf_selection_counts, tables_dir / "walk_forward_selection_counts.csv")
        _save_table(wf_yearly, tables_dir / "walk_forward_yearly.csv")

        save_equity_curve(
            tvt["bt_test"],
            DATE_COL,
            figures_dir / "final_test_equity_curve.png",
            "Final Test Equity Curve",
        )
        save_drawdown_curve(
            tvt["bt_test"],
            DATE_COL,
            figures_dir / "final_test_drawdown.png",
            "Final Test Drawdown",
        )
        save_equity_curve(
            wf_results,
            DATE_COL,
            figures_dir / "walk_forward_equity_curve.png",
            "Walk-Forward Equity Curve",
        )
        save_drawdown_curve(
            wf_results,
            DATE_COL,
            figures_dir / "walk_forward_drawdown.png",
            "Walk-Forward Drawdown",
        )
        save_yearly_bar_chart(
            wf_yearly,
            figures_dir / "walk_forward_yearly_returns.png",
            "Walk-Forward Yearly Returns",
        )
        _write_summary(
            output_dir / "summary.md",
            config,
            directional_corr,
            baseline_regression,
            tvt,
            wf_summary,
            wf_diagnostics,
            wf_selection_counts,
        )

    return outputs
